owner: Hans5958
repo: Scratch-Upptime-2

sites:
  - name: Scratch Lab
    url: https://lab.scratch.mit.edu
  - name: ScratchX
    url: https://scratchx.org
  - name: ScratchJr
    url: https://www.scratchjr.org
  - name: ScratchEd
    url: http://scratched.gse.harvard.edu
  - name: Scratch Foundation
    url: https://scratchfoundation.org
  - name: Scratch Day website
    url: https://day.scratch.mit.edu
  - name: Scratch in Practice website
    url: https://sip.scratch.mit.edu
  - name: Test website
    url: https://scratch.ly
    expectedStatusCodes:
      - 403
  - name: Test download server
    url: https://downloads.scratch.ly
  - name: Assets CDN server
    url: https://cdn.assets.scratch.mit.edu
  - name: Project CDN server
    url: https://cdn.projects.scratch.mit.edu
  - name: "Redirect: scratch.org"
    url: https://scratch.org
  - name: "Redirect: scratch.love"
    url: https://scratch.love
  - name: "Redirect: scratch.computer"
    url: https://scratch.computer
  - name: "Redirect: scratch.chat"
    url: https://scratch.chat
  - name: "Redirect: scratch.land"
    url: https://scratch.land
  - name: "Redirect: scratch.rest"
    url: https://scratch.rest
  - name: "Redirect: scratch.team"
    url: https://scratch.team
  - name: "Redirect: scratch.camp"
    url: https://scratch.camp
  - name: "Redirect: scratch.pizza"
    url: https://scratch.pizza

status-website:
  name: Scratch Upptime 2 (unofficial)
  cname: scratch-upptime-2.netlify.app
  introTitle: Welcome to **[Scratch](https://scratch.mit.edu)**'s second (unofficial) Upptime status page.
  introMessage: This is the status page for less-known services related to [Scratch](https://scratch.mit.edu). It monitors them for free using GitHub services, thanks to [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Auto5958
commitMessages:
  commitAuthorName: Auto5958
  commitAuthorEmail: 69833949+Auto5958@users.noreply.github.com
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
