owner: Hans5958
repo: Scratch-Upptime-2

sites:
  - name: Assets CDN server
    url: https://cdn.assets.scratch.mit.edu
  - name: Project CDN server
    url: https://cdn.projects.scratch.mit.edu

status-website:
  name: Scratch Upptime 2 (unofficial)
  cname: scratch-upptime-2.netlify.app
  introTitle: Welcome to **[Scratch](https://scratch.mit.edu)**'s second (unofficial) Upptime status page.
  introMessage: This is the status page for less-known services related to [Scratch](https://scratch.mit.edu). It monitors them for free using GitHub services, thanks to [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Auto5958
commitMessages:
  commitAuthorName: Auto5958
  commitAuthorEmail: 69833949+Auto5958@users.noreply.github.com
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true